# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=140)),
                ('propietario', models.CharField(max_length=140)),
                ('activo', models.BooleanField(default=True)),
                ('issue', models.TextField()),
                ('fecha', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('recibido', 'Recibido'), ('en proceso', 'En Proceso'), ('atendido', 'Atendido')], default='recibido', max_length=140)),
                ('foto', models.ImageField(upload_to='fotitos')),
            ],
        ),
    ]
